medeir_site/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [path('display',views.index, name = 'index'),
              path('entry',views.entry,name = 'entry'),]

polls/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Import(models.Model):
    img_name = models.CharField(max_length=200)
    #pub_date = models.DateTimeField('date published')
    image = models.FileField(upload_to='images/corrupted/')

    def __str__(self):
        return self.img_name

class Slice(models.Model):
    img_name = models.CharField(max_length=200)
    #pub_date = models.DateTimeField('date published')
    image = models.FileField(upload_to='images/slices/')

    def __str__(self):
        return self.img_name

polls/forms.py
from django import forms

from .models import Import

class ImportForm(forms.ModelForm):
    class Meta:
        model = Import
        fields = "__all__"

polls/views.py
from multiprocessing import context
from tkinter import image_names
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings

from .models import Import
from .models import Slice
import nibabel as nib
import numpy as np
from PIL import Image

from .forms import ImportForm
# Create your views here.

def index(request):
    images_list = Import.objects.all()
    image_urls = [img.image.url for img in images_list]
    # print(image_urls[0], "bbbbbbbbbbbb")
    # print(settings.MEDIA_ROOT, "aaaaaaaaaaaaaaaaaaa")
    # print("/".join(images_list[0].image.url.split("/")[2::]),'eeeeeeeee')

    media_root = settings.MEDIA_ROOT
    
    slices_list = Slice.objects.all()
    slices_list.delete()

    for cor_images in images_list:
        im_url = "/".join(cor_images.image.url.split("/")[2::])
        im = nib.load(media_root + im_url)
        num_img = np.array(im.dataobj)
        im_jpg = Image.fromarray(np.multiply(num_img[75],255))
        im_jpg = im_jpg.convert('L')


        img_path = media_root + im_url.replace("corrupted","slices").replace(".nii.gz",".jpeg")
        im_jpg.save(img_path)
        slice_path = "images/slices/" + im_url.split("/")[-1].replace(".nii.gz",".jpeg")
        new_slice = Slice(img_name = cor_images.img_name,image = slice_path)
        new_slice.save()

    slices_list = Slice.objects.all()


    #context = {'images_list':images_list,'slices_list':slices_list,'length':range(len(slices_list))}
    context = {'list':zip(images_list,slices_list)} 
    return render(request,"polls/index.html",context)

def entry(request):
    if request.method == "POST":
        form = ImportForm(request.POST,request.FILES)

        if form.is_valid:
            form.save()
        
        return redirect("polls:entry")

    form = ImportForm()
    context = {'image_form':form }
    return render(request, "polls/entry.html", context)

polls/templates/polls/entry.html
<!DOCTYPE html>
<html>
  <head>
    <!--  The head contains Meta-data -->
    <!-- Use html+Tab to get the boilerplate  -->
    <!-- Use cmd+/ to get the html comment line -->
    <meta charset="utf-8">
    <title> This is the Title! </title>
  </head>
  <body>
    <!-- The body contains the actual content -->
    {% load crispy_forms_tags %}  
          <h2>Add a new image</h2>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{image_form|crispy}}
                <button type="submit">Submit</button>
          </form>

        <a href = "{% url 'polls:index' %}">Display</a>
        
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <!--  The head contains Meta-data -->
    <!-- Use html+Tab to get the boilerplate  -->
    <!-- Use cmd+/ to get the html comment line -->
    <meta charset="utf-8">
    <title> This is the Title! </title>
  </head>
  <body>
    <!-- The body contains the actual content -->
    {% if list %}
        <ul>
        {% for i in list %}
            <li><a href="{{ i.0.image.url }}/">{{ i.0.img_name }}</a>

            <img src="{{ i.1.image.url }}" ></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href = "{% url 'polls:entry' %}">Entry form</a>
  </body>
</html>




